# Generated by Django 5.2.17 on 2026-09-11 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("project_name", models.CharField(max_length=255)),
                ("token_symbol", models.CharField(max_length=16)),
                ("chain_id", models.PositiveIntegerField()),
                ("budget", models.DecimalField(decimal_places=18, max_digits=40)),
                (
                    "remaining_budget",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                (
                    "reward_model",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed per post"),
                            ("IMPRESSION_BASED", "Per 1k impressions"),
                            ("ENGAGEMENT_BASED", "Per 100 engagements"),
                            ("HYBRID", "Fixed + engagement"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reward_rate",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                (
                    "maximum_reward_per_seller",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                ("maximum_rewards_per_seller", models.PositiveIntegerField(default=0)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ENDED", "Ended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("requirements_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LEFT", "Left"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cumulative_reward",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "unique_together": {("seller", "campaign")},
            },
        ),
    ]
