# Generated by Django 5.2.17 on 2026-09-12 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignparticipation",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participations",
                to="sellers.sellerprofile",
            ),
        ),
    ]
