# Generated by Django 5.2.17 on 2026-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_alter_campaignparticipation_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="discovery_watermarks",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
