# Generated by Django 5.2.17 on 2026-10-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_brandprofile_brandfunding"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="funding_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="campaigns.brandprofile",
            ),
        ),
        migrations.AlterField(
            model_name="brandfunding",
            name="amount",
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
    ]
