# Generated by Django 5.2.17 on 2026-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaign_funding_brand_alter_brandfunding_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandfunding",
            name="token_symbol",
            field=models.CharField(default="USDG", max_length=16),
        ),
    ]
