# Generated by Django 5.2.17 on 2026-10-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_alter_brandfunding_token_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandfunding",
            name="verified_amount",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=40, null=True
            ),
        ),
        migrations.AddField(
            model_name="brandfunding",
            name="verified_block",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brandfunding",
            name="verified_confirmations",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brandfunding",
            name="verified_sender",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
