# Generated by Django 5.2.17 on 2026-09-11 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("username", models.CharField(max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("avatar_url", models.URLField(blank=True)),
                ("encrypted_credentials", models.BinaryField(blank=True)),
                ("credentials_iv", models.BinaryField(blank=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "connected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="CONNECTED", max_length=16)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_accounts",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_post_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("post_url", models.URLField()),
                ("text_snapshot", models.TextField(blank=True)),
                ("published_at", models.DateTimeField()),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("DISCOVERED", "Discovered"),
                            ("BASIC_VALIDATION", "Basic validation"),
                            ("CAMPAIGN_MATCH", "Campaign match"),
                            ("DUPLICATE_CHECK", "Duplicate check"),
                            ("METRICS_PENDING", "Metrics pending"),
                            ("VERIFIED", "Verified"),
                            ("REWARD_CALCULATED", "Reward calculated"),
                            ("APPROVED", "Approved"),
                            ("NOT_ELIGIBLE", "Not eligible"),
                            ("DUPLICATE", "Duplicate"),
                            ("OUTSIDE_CAMPAIGN_WINDOW", "Outside campaign window"),
                            ("REQUIREMENT_MISSING", "Requirement missing"),
                            ("ACCOUNT_NOT_CONNECTED", "Account not connected"),
                            ("PROVIDER_ERROR", "Provider error"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious activity"),
                        ],
                        db_index=True,
                        default="DISCOVERED",
                        max_length=32,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("last_metrics_sync", models.DateTimeField(blank=True, null=True)),
                ("impressions", models.BigIntegerField(default=0)),
                ("likes", models.BigIntegerField(default=0)),
                ("reposts", models.BigIntegerField(default=0)),
                ("replies", models.BigIntegerField(default=0)),
                ("quotes", models.BigIntegerField(default=0)),
                ("bookmarks", models.BigIntegerField(default=0)),
                ("total_engagement", models.BigIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="sellers.sellerprofile",
                    ),
                ),
                (
                    "x_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="social.xaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="PostMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("likes", models.BigIntegerField(default=0)),
                ("reposts", models.BigIntegerField(default=0)),
                ("replies", models.BigIntegerField(default=0)),
                ("quotes", models.BigIntegerField(default=0)),
                ("bookmarks", models.BigIntegerField(default=0)),
                ("raw_provider_payload", models.JSONField(blank=True, default=dict)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="social.socialpost",
                    ),
                ),
            ],
            options={
                "ordering": ["collected_at"],
                "unique_together": {("post", "collected_at")},
            },
        ),
    ]
