# Generated by Django 5.2.17 on 2026-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
