# Generated by Django 5.2.17 on 2026-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_platform_aware_social"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="is_quote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="is_repost",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="socialpost",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("DISCOVERED", "Discovered"),
                    ("BASIC_VALIDATION", "Basic validation"),
                    ("CAMPAIGN_MATCH", "Campaign match"),
                    ("DUPLICATE_CHECK", "Duplicate check"),
                    ("METRICS_PENDING", "Metrics pending"),
                    ("VERIFIED", "Verified"),
                    ("REWARD_CALCULATED", "Reward calculated"),
                    ("APPROVED", "Approved"),
                    ("NOT_ELIGIBLE", "Not eligible"),
                    ("DUPLICATE", "Duplicate"),
                    ("OUTSIDE_CAMPAIGN_WINDOW", "Outside campaign window"),
                    ("REQUIREMENT_MISSING", "Requirement missing"),
                    ("NOT_ORIGINAL", "Not original (repost or quote)"),
                    ("NOT_DISCLOSED", "Required disclosure missing"),
                    ("ACCOUNT_NOT_CONNECTED", "Account not connected"),
                    ("PROVIDER_ERROR", "Provider error"),
                    ("SUSPICIOUS_ACTIVITY", "Suspicious activity"),
                ],
                db_index=True,
                default="DISCOVERED",
                max_length=32,
            ),
        ),
    ]
