# Generated by Django 5.2.17 on 2026-09-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_socialpost_is_quote_socialpost_is_repost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="originality_evidence",
            field=models.CharField(
                choices=[
                    ("SELF_REPORTED", "Self-reported (never checked)"),
                    ("PROVIDER_CONFIRMED", "Confirmed by provider"),
                    ("PROVIDER_REJECTED", "Rejected by provider"),
                    ("PROVIDER_UNAVAILABLE", "Provider unavailable"),
                ],
                default="SELF_REPORTED",
                max_length=24,
            ),
        ),
    ]
