# Generated by Django 5.2.17 on 2026-09-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Heartbeat",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "heartbeat",
            },
        ),
    ]
