# Generated by Django 5.2.17 on 2026-09-11 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rewards", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=42)),
                ("chain_id", models.PositiveIntegerField()),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("sepolia", "Sepolia (testnet)"),
                            ("mainnet", "Ethereum mainnet"),
                        ],
                        default="sepolia",
                        max_length=16,
                    ),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[("EVM", "EVM")], default="EVM", max_length=8
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("nonce", models.CharField(blank=True, max_length=128)),
                (
                    "connected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
                "unique_together": {("seller", "address", "chain_id")},
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=18, max_digits=40)),
                (
                    "amount_smallest_unit",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("token_symbol", models.CharField(max_length=16)),
                ("chain_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("SIGNING", "Signing"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                            ("REPLACED", "Replaced"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="CREATED",
                        max_length=16,
                    ),
                ),
                ("nonce", models.CharField(blank=True, editable=False, max_length=128)),
                ("signed_authorization", models.TextField(blank=True, editable=False)),
                ("transaction_hash", models.CharField(blank=True, max_length=66)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reward",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim",
                        to="rewards.reward",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="sellers.sellerprofile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["CREATED", "SIGNING", "SUBMITTED", "PENDING"],
                            )
                        ),
                        fields=("reward", "status"),
                        name="unique_open_claim_per_reward",
                    )
                ],
            },
        ),
    ]
