# Generated by Django 5.2.17 on 2026-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
