# Generated by Django 5.2.17 on 2026-09-11 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("sellers", "0001_initial"),
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=18, max_digits=40)),
                ("gross_amount", models.DecimalField(decimal_places=18, max_digits=40)),
                (
                    "deduction_amount",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                ("currency", models.CharField(default="USDT", max_length=16)),
                ("token_symbol", models.CharField(max_length=16)),
                ("chain_id", models.PositiveIntegerField()),
                (
                    "calculation_version",
                    models.CharField(
                        choices=[("V1", "Calculation version 1")],
                        default="V1",
                        max_length=8,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending verification"),
                            ("VERIFIED", "Verified"),
                            ("APPROVED", "Approved"),
                            ("AVAILABLE", "Available to claim"),
                            ("CLAIMED", "Claimed"),
                            ("FAILED", "Claim failed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reversal_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rewards",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward",
                        to="social.socialpost",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rewards",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["PENDING", "VERIFIED", "APPROVED", "AVAILABLE"],
                            )
                        ),
                        fields=("post", "status"),
                        name="unique_live_reward_per_post",
                    )
                ],
            },
        ),
    ]
