# Generated by Django 5.2.17 on 2026-09-17 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rewards", "0001_initial"),
        ("sellers", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="claiming", max_length=64, unique=True),
                ),
                ("claiming_paused", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TokenConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=16, unique=True)),
                ("chain_id", models.PositiveIntegerField(db_index=True)),
                ("address", models.CharField(max_length=42, unique=True)),
                ("decimals", models.PositiveSmallIntegerField(default=18)),
                (
                    "minimum_claim",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                (
                    "maximum_claim",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("REWARD_EARNED", "Reward earned"),
                            ("REWARD_APPROVED", "Reward approved"),
                            ("CLAIM_CREATED", "Claim created"),
                            ("CLAIM_CONFIRMED", "Claim confirmed on-chain"),
                            ("CLAIM_FAILED", "Claim failed"),
                            ("RECONCILIATION", "Reconciliation note"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("token_symbol", models.CharField(blank=True, max_length=16)),
                (
                    "amount",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                ("amount_smallest_unit", models.BigIntegerField(default=0)),
                ("transaction_hash", models.CharField(blank=True, max_length=66)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="wallets.claim",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="rewards.reward",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="sellers.sellerprofile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
