# Generated by Django 5.2.17 on 2026-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("REWARD_EARNED", "Reward earned"),
                    ("REWARD_APPROVED", "Reward approved"),
                    ("CLAIM_CREATED", "Claim created"),
                    ("CLAIM_CONFIRMED", "Claim confirmed on-chain"),
                    ("CLAIM_FAILED", "Claim failed"),
                    ("FEE_ACCRUED", "Platform fee accrued to treasury"),
                    ("RECONCILIATION", "Reconciliation note"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
